### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' on python 3.6.8 version

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [palashsharma891/ImageSort#1]
I tried to use code on python 3.6.8 version and I get error.
< date = str(datetime.strptime(match.group(), '%Y-%m-%d').date()) # OR %Y%m%d For images saved like: IMG_20200720
AttributeError: 'NoneType' object has no attribute 'group'>

**Comment by palashsharma891** [comment]
How are images saved on you system?(IMG_20200720, IMG2020-07-20, etc.) Also, on which OS are you?

**Comment by MindaugasVaitkus2** [comment]
Files are saved as IMG_20200720, IMG2020-07-20, My PC has Windows 10 PRO 64-bit OS.

**Comment by palashsharma891** [comment]
I have made changes for both kinds of filenames now. Kindly check again with the new code.

**Comment by MindaugasVaitkus2** [comment]
I tested new code and got error.

```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\1A.py", line 44, in <module>
    date = str(datetime.strptime(match2.group(), '%Y%m%d').date()) # OR %Y%m%d For images saved like: IMG_20200720
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 6
```

**Comment by palashsharma891** [comment]
Oh sorry. For Windows, you would have to use the commented code. And please use os.getcwd() in the beginning. Sorry for not pointing this out earlier.

**Comment by MindaugasVaitkus2** [comment]
I understood, looks I have to change regex code for files naming. But for single folder why don't you use "for images in os.listdir ( parent_dir )"?

**Comment by palashsharma891** [comment]
No, you would not need to change regex, because I have added a new if statement for that. You would just have to add '\\' and use os.getcwd() instead.
I did not use os.listdir() because I was unaware of it. I had just learnt about the os library that day. Thanks for this. Now I'll go add this to the code.

**Comment by MindaugasVaitkus2** [comment]
I understood. But you can use regex only for few names scenarios, but if you have many dates formats then multiple regexes matches also applying try and error method can be best solution.

**Comment by palashsharma891** [comment]
Yes, I suppose you could do that. I only had access to Windows and Ubuntu, and only these 2 kinds of image names, so I did the best I could do in a short span of time.
